# Iris Data Set

In [1]:
import io
import pandas as pd

In [2]:
!pip install ipython-autotime --index-url https://pypi.org/simple

In [3]:
%load_ext autotime

time: 492 μs (started: 2025-07-15 08:10:21 +00:00)


In [8]:
import os
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"
columns = ['F1', 'F2' , 'F3' , 'F4', 'Label']
df = pd.read_csv(url, header=None, names=columns)

#Define the output path and create directories if they don't exist
output_dir = 'dataset'
output_path = os.path.join(output_dir, 'iris.csv')

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Save the dataset to Google Drive as a CSV file
df.to_csv(output_path, index=False)

print(f"Dataset saved to {output_path}")

Dataset saved to dataset/iris.csv
time: 125 ms (started: 2025-07-15 08:22:27 +00:00)


In [11]:
sample_df = pd.read_csv('dataset/iris.csv', header=0)

time: 11.3 ms (started: 2025-07-15 08:22:45 +00:00)


In [12]:
sample_df.head()

F1   F2   F3   F4        Label
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

time: 27.9 ms (started: 2025-07-15 08:22:49 +00:00)


In [20]:
import torch
import numpy as np
from sklearn.preprocessing import LabelEncoder

dataset = sample_df.values

X = dataset[:,0:4].astype(float)
Y = dataset[:,4]

# Print the NumPy arrays
print("NumPy X:", X)
print("NumPy Y:", Y)

# Step 4: Convert NumPy arrays to PyTorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32)

label_encoder = LabelEncoder()
Y_encoded = label_encoder.fit_transform(Y)  # Convert string labels to integers

# Convert Y_encoded to tensor with int64 type, and reshape it
Y_tensor = torch.tensor(Y_encoded, dtype=torch.int64).view(-1, 1)  # Y_tensor is reshaped to ensure compatibility with the model's output and loss calculation


# Print the PyTorch tensors
print("PyTorch X_tensor:", X_tensor)
print("PyTorch Y_tensor:", Y_tensor)

NumPy X: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6